### ISSUE TITLE
Screens no longer indicate which deck is assigned as Tempo Master

### ISSUE THREAD

**Issue by djBraveDave** [ErikMinekus/traktor-kontrol-screens#15]
The title is pretty self explanatory. 
Not sure if this is intentional or not, but this handy feature from the original version no longer works. Re-enabling it would be a fantastic improvement! 

<img width="517" alt="Screen Shot 2020-03-26 at 11 50 54 AM" src="https://user-images.githubusercontent.com/62711512/77668769-3844e380-6f5a-11ea-8421-227b4440f70e.png">

P.-S. Incredibly impressed by your work! Let me know how I can send you a donation as a token of gratitude. Thank you for your time! I will keep sending constructive feedback if you're interested.

**Comment by ErikMinekus** [comment]
Correct, I removed it because it hides the pitch percentage, and you can already see if you're on the master deck by holding down Shift and looking at the Sync button.

If you want a permanent sync/master indicator, check out https://github.com/kokernutz/traktor-kontrol-screens.

You can donate at https://www.paypal.me/ErikMinekus. Much appreciated!
