### ISSUE TITLE
Help needed - Inverted BPM adjust speed (Shift/No Shift) on S5

### ISSUE THREAD

**Issue by amandryka** [ErikMinekus/traktor-kontrol-screens#16]
I'm trying to understand the code, and trying add the modification of BPM adjustment to go 1 per without holding shift.

Is this done with the following lines?
in S5Deck.qml

>           Wire { from: "%surface%.browse"; to: "decks.1.tempo.fine";   enabled:  module.shift }
>           Wire { from: "%surface%.browse"; to: "decks.1.tempo.coarse"; enabled: !module.shift }

I see that you have them repeated for each deck, how about Master BPM and the Tempo encoder?

Also, is there any risk to brick my S5 by messing the .qml around or is it safe to experiment?

Thanks a lot!

**Comment by ErikMinekus** [comment]
Yes, those are the correct lines. You can find similar lines for the Master Tempo knob in `CSI/S5/Mixer.qml`.

You can't physically damage your S5 by changing the QML files. If you make a mistake your S5 will likely display blue screens, or Traktor may crash on startup. That's why it's important to keep a backup of the original files.

**Comment by amandryka** [comment]
Yeah! I was able to switch it up, thanks!
Do you know any resource about the different functions/objects I can use in terms of button/pad/knob?
