### ISSUE TITLE
Match musical key value that is set in Traktor preferences

### ISSUE THREAD

**Issue by alza-bitz** [ErikMinekus/traktor-kontrol-screens#5]
Hi there,

It would be useful if the screens matched the musical key style that is set in Traktor preferences.

For example, if the musical key is set in the Traktor preferences to "Open Key", then the screens would use open key notation instead of Camelot key.

This would match what is set in Traktor.

**Comment by ErikMinekus** [comment]
Unfortunately there is no documentation on how to read most of the settings. Also there is no Camelot Key option in Traktor preferences. But I'll consider adding a preferences file.

**Comment by starchild** [comment]
Agreed, displaying both notation types is more confusing than helpful.

**Comment by alzadude** [comment]
Hi @ErikMinekus as a quicker fix, rather than a preferences file, is there any chance the screens could be changed to just use open key notation? As you mentioned, Traktor doesn't have Camelot Key anyway so this is not a good option since it will never match.. also I am guessing that most Traktor DJs would prefer open key rather than musical key, since it's easier to understand and work with (for non musically-trained people) 🙂

**Comment by ErikMinekus** [comment]
The original displays already display the Open Key notation if you have it set in Traktor's preferences, so there's no need to use my mods then.

**Comment by ErikMinekus** [comment]
I have now added a preferences file, where you can disable Camelot Keys.
